### ISSUE TITLE
Example doesn't work without server (in Chrome)

### ISSUE THREAD

**Issue by naartjie** [jchavarri/jsoo-react#32]
Hi @jchavarri, thanks for starting this great project. Exciting stuff!!

Running the example without the server (using Chrome), something is failing with the router / pushState:

<img width="1184" alt="Screenshot 2019-10-13 at 21 50 56" src="https://user-images.githubusercontent.com/514563/66721368-ac078f80-ee03-11e9-8af1-a68c58987719.png">

Running the server works fine.

**Comment by jchavarri** [comment]
Hi @naartjie , thanks for the kind words :) 

`history` functions don't work when opening an html local file with `file://`, and because `reason-react` and thus `jsoo-react` rely on `history.pushState`, the examples can't work without a local server.

I will keep this issue open as a reminder to update the readme. :)

**Comment by jchavarri** [comment]
The readme now mentions that it's required to start a server to run the example:

https://github.com/jchavarri/jsoo-react/blob/94e7d95d545fc21550ff9358a147818d53389c6b/README.md#L41-L42
